spring:
  application:
    name: csv-team-stats-persistence
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:csv-team-stats-persistence}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
      specific.avro.reader: true
app:
  kafka:
    topics:
      parsed-team-stats: ${KAFKA_PARSED_TEAM_STATS_TOPIC:team-stats.parsed}
