{"namespace":"com.example.csvteamstats.avro","type":"record","name":"TeamStatsValue","fields":[{"name":"sourceEventId","type":"string"},{"name":"matchId","type":"string"},{"name":"period","type":"string"},{"name":"category","type":"string"},{"name":"metric","type":"string"},{"name":"homeTeam","type":"string"},{"name":"homeValue","type":["null","string"],"default":null},{"name":"awayTeam","type":"string"},{"name":"awayValue","type":["null","string"],"default":null},{"name":"sourceUrl","type":["null","string"],"default":null}]}